# Generated by Django 3.0.4 on 2020-04-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200416_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='steps',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
