# Generated by Django 3.0.4 on 2020-04-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200418_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='steps',
            field=models.TextField(blank=True),
        ),
    ]
